version: "2.4"

################################################################################

services:
  h1: # image name : PROJECT_h1
    container_name: h1 # container name: h1
    runtime: nvidia
    privileged: true
    environment:
      # Display X Server GUI.
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      # Configure Nvidia Docker interface.
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_REQUIRE_CUDA=cuda>=11.0
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    shm_size: '8gb' # Docker イメージ構築時に割り当てる共有メモリの容量
    volumes:
      # Mount the project directory.
      - ../:/root/improbable
      # Grant display access to X Server.
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
    tty: true
    # command: tail -f /dev/null # コンテナ起動時に実行するコマンド
    # command: bash
    # command: ["/ros_entrypoint.sh", "bash"] 